// importing all models
const Admin = require("./models/admin");
const ChemicalCompound = require("./models/chemicalCompound");
const Suppliers = require("./models/Suppliers");
const RawMaterials = require("./models/rawMaterial");
const employees = require("./models/employees");
const machines = require("./models/machineryParts");
const wholesale = require("./models/wholesaleOrder");
const products = require("./models/products");
const safety = require("./models/safetyEquipment");
