// importing all models
const Admin = require("./admin");
const ChemicalCompound = require("./chemicalCompound");
const Suppliers = require("./Suppliers");
const RawMaterials = require("./rawMaterial");
const employees = require("./employee");
const machines = require("./machineryPart");
const wholesale = require("./wholesaleOrder");
const products = require("./products");
const safety = require("./safetyEquipment");
